### ISSUE TITLE
fn with_lock<F, U> where  F: FnMut 

### ISSUE THREAD

**Issue by frehberg** [Milo123459/with_lock#2]
Current definition is
```
	pub fn with_lock<F, U>(&self, function: F) -> U
	where
		F: FnOnce(&mut T) -> U,
```
EDIT:

FnOnce will not permit Closures/Lambdas with captured mutable variables/state. Declaring 'function' as FnOnce, captured variables will be "consumed" by the invokation. The 'function" will not be able to share state between invocations., for example counting the number of calls.

The following test is failing, as the function "action_and_get" does not hold the state of "count", being of type FnOnce.  Instead being 11 the final sum is 10. It seems, Rust is creating a new instance for every invocation of action_and_get, and afterwards destroying the FnOnce-Instance including the state of "count".

```

	#[test]
	fn test_with_lock_capture_mut() {
		let a = WithLock::<SharedData>::new(Mutex::new(SharedData { a: 2, b: 2 }));
		let mut count : i32 = 0;

		let action_and_get = move |s: &mut SharedData| {
			count += 1;
			let sum = (*s).a + (*s).b + count;
			sum
		};
		let a_lock = a.with_lock(action_and_get);
		let a_lock_2 = a.with_lock(action_and_get);

		assert_eq!(a_lock + a_lock_2, 11);
	}

```
Instead of FnOnce, the 'function' should be declared as FnMut, so that the function would be able to modify other mutable captured data, such as the captured "count" variable.

**Comment by Milo123459** [comment]
Allowing it to edit other mutable pieces of data could cause deadlocks. Unless there is a specific way around this, I don't think we should do this.

**Comment by frehberg** [comment]
mem::forget(Kestrer) at discord explained to me why  the code above is working:
 
> Today at 8:20 PM
> What's happening is that the closure gets copied each time you pass it into with_lock
> That's because it implements Copy
> closures automatically do when applicable 
> You have to pass in &mut action_and_get to avoid that behaviour

AFAICS, the  API as it is now is misleading, and users might run into the same issue as I did with the captured "count"

**Comment by Milo123459** [comment]
🤔 I'm not sure how it is misleading - but I can see your point from that edge case you posted in the original description of the issue. Feel free to make a PR implementing this, I'm a tad busy for the next couple of days. 
Also, this needs to ensure that no previous working code is broken. I know it shouldn't, but this shouldn't require any test changes.

BTW, how did you find out about with_lock? Just a little curious :)

**Comment by Milo123459** [comment]
I'm back to working on this project. Does this still effect you?
